version: '3.5'

services:

  discovery:
    image: hrms/discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image:  hrms/gateway-service
    container_name: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  zipkin-service:
    image:  hrms/zipkin-service
    container_name: zipkin-service
    build:
      context: ./zipkin-service
      dockerfile: Dockerfile
    ports:
      - "9411:9411"

  employee-service:
    image: hrms/employee-service
    container_name: employee-service
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    ports:
      - "1111:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  position-service:
    image: hrms/position-service
    container_name: position-service
    build:
      context: ./position-service
      dockerfile: Dockerfile
    ports:
      - "3333:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery
  
  recruitement-service:
    image: hrms/recruitement-service
    container_name: recruitement-service
    build:
      context: ./recruitement-service
      dockerfile: Dockerfile
    ports:
      - "4444:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery
  account-service:
    image: piomin/account-service
    container_name: account-service
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "8541:8541"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  customer-service:
    image: piomin/customer-service
    container_name: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8542:8542"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery
  conge-service:
    image: hrms/conge-service
    container_name: conge-service
    build:
      context: ./conge-service
      dockerfile: Dockerfile
    ports:
      - "5555:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery
  
  contrat-service:
    image: hrms/contrat-service
    container_name: contrat-service
    build:
      context: ./contrat-service
      dockerfile: Dockerfile
    ports:
      - "2222:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery

  mongo:
    container_name: mongo-db
    image: "mongo:5-focal"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    hostname: mongo


  auth-service:
    image: hrms/auth-service
    container_name: auth-service
    ports:
      - "6666:3000"
    hostname: auth
    depends_on:
      - "mongo"

volumes:
   mongodb_data_container: