version: '3.5'
services:

  discovery:
    image: hrms/discovery-service
    container_name: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  gateway:
    image:  hrms/gateway-service
    container_name: service-gateway
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery:8761/eureka
    links:
      - discovery
