info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  prefix: /api
  routes:
    employee:
      path: /employees/**
      serviceId: employee-service
    payroll:
      path: /payrolls/**
      serviceId: payroll-service
    position:
      path: /positions/**
      serviceId: position-service
    recruitement:
      path: /recruitements/**
      serviceId: recruitement-service
    leave-holiday:
      path: /leave-holidays/**
      serviceId: leave-holiday-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG