info:
  component: Edge Server

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

# spring : 
#    security:
#      user:
#       name: user
#       password: user

zuul:
  prefix: /api
  routes:
    employee:
      path: /employees/**
      serviceId: employee-service
    payroll:
      path: /contrats/**
      serviceId: contract-service
    position:
      path: /positions/**
      serviceId: position-service
    recruitement:
      path: /recruitements/**
      serviceId: recruitement-service
    conges:
      path: /conges/**
      serviceId: conge-service
    account:
      path: /accounts/**
      serviceId: account-service
    customer:
      path: /customers/**
      serviceId: customer-service

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: false

server:
  port: 8765

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG