server:
  port: ${PORT:4444}
  
spring:
  datasource:
        password: password
        url: jdbc:h2:dev
        username: SA

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true